# Generated by Django 6.0.2 on 2026-02-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=50, unique=True)),
                ('bank_id', models.CharField(max_length=100, unique=True)),
                ('type_maladie', models.CharField(blank=True, max_length=100, null=True)),
                ('pwd', models.CharField(max_length=255)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('face_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('bank_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mara_tech.user', to_field='bank_id')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='HistBanque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bid_reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to='mara_tech.user', to_field='bank_id')),
                ('bid_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sent', to='mara_tech.user', to_field='bank_id')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('localisation', models.CharField(max_length=255)),
                ('quantité', models.IntegerField()),
                ('prix_totale', models.DecimalField(decimal_places=2, max_digits=15)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mara_tech.produit')),
            ],
        ),
    ]
